# SPDX-FileCopyrightText: (c) 2025 Xronos Inc. Licensed to DENSO International America, Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
# render instance host addresses
# hostname precedence: <deployment>-avp-render, groups['avp_render'][0]
# public address precedence: ec2_public_ip, ansible_ssh_host
# private address precedence: ec2_private_ip, ansible_ssh_host
avp_render_inventory_name: "{{ 
  hostvars[deployment ~ '-avp-render']['inventory_hostname']
  | default(groups['avp_render'][0]['inventory_hostname']) }}"
avp_render_host_public: "{{ 
  hostvars[avp_render_inventory_name]['ec2_public_ip']
  | default(hostvars[avp_render_inventory_name].ansible_ssh_host) }}"
avp_render_host_private: "{{
  hostvars[avp_render_inventory_name]['ec2_private_ip']
  | default(hostvars[avp_render_inventory_name].ansible_ssh_host) }}"

# ewaol instance host addresses
# hostname precedence: <deployment>-avp-ewaol, groups['avp_ewaol'][0]
# public address precedence: ec2_public_ip, ansible_ssh_host
# private address precedence: ec2_private_ip, ansible_ssh_host
avp_ewaol_inventory_name: "{{ 
  hostvars[deployment ~ '-avp-ewaol']['inventory_hostname']
  | default(groups['avp_ewaol'][0]['inventory_hostname']) }}"
avp_ewaol_host_public: "{{ 
  hostvars[avp_ewaol_inventory_name]['ec2_public_ip']
  | default(hostvars[avp_ewaol_inventory_name].ansible_ssh_host) }}"
avp_ewaol_host_private: "{{
  hostvars[avp_ewaol_inventory_name]['ec2_private_ip']
  | default(hostvars[avp_ewaol_inventory_name].ansible_ssh_host) }}"

# xronos-dashboard instance host addresses
# hostname precedence: <deployment>-avp-render, groups['dashboard'][0]
# public address precedence: ec2_public_ip, ansible_ssh_host
# private address precedence: ec2_private_ip, ansible_ssh_host
xronos_dashboard_inventory_name: "{{ 
  hostvars[deployment ~ '-xronos-dashboard']['inventory_hostname']
  | default(groups['dashboard'][0]['inventory_hostname']) }}"
xronos_dashboard_host_public: "{{ 
  hostvars[xronos_dashboard_inventory_name]['ec2_public_ip']
  | default(hostvars[xronos_dashboard_inventory_name].ansible_ssh_host) }}"
xronos_dashboard_host_private: "{{
  hostvars[xronos_dashboard_inventory_name]['ec2_private_ip']
  | default(hostvars[xronos_dashboard_inventory_name].ansible_ssh_host) }}"