# SPDX-FileCopyrightText: (c) 2025 Xronos Inc. Licensed to DENSO International America, Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Apt add deadsnakes PPA
  register: _deadsnakes_ppa
  become: true
  ansible.builtin.template:
    src: deadsnakes-ubuntu-ppa.sources
    dest: /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-{{ ansible_distribution_release }}.sources
    mode: u=rw,g=r,o=r

- name: Apt update cache
  when: _deadsnakes_ppa.changed
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install Python3.10
  become: true
  ansible.builtin.apt:
    name:
      - python3.10-dev
      - python3.10-venv
