# SPDX-FileCopyrightText: (c) 2025 Xronos Inc. Licensed to DENSO International America, Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Create group soafee
  become: true
  ansible.builtin.group:
    name: soafee

- name: Configure user {{ ansible_user }}
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups:
      - soafee

- name: Reset connection to apply user change
  changed_when: false
  ansible.builtin.meta:
    reset_connection
