# SPDX-FileCopyrightText: (c) 2025 Xronos Inc. Licensed to DENSO International America, Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
galaxy_info:
  role_name: configure_render
  company: Xronos, Inc.
  author: Jeff C. Jensen
  description: "Ansible role to install Autoware.Auto AVP demo on render instances"
  license: proprietery
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
collections:
  - community.docker
  - kubernetes.core
