# SPDX-FileCopyrightText: (c) 2025 Xronos Inc. Licensed to DENSO International America, Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- hosts: avp_builder
  gather_facts: true
  roles:
    - name: deconfigure_ecr
      role: deconfigure_ecr
